from stickertaggerbot.handlers.callbacks import create_callback_handler
from stickertaggerbot.handlers.inline_query import create_inline_query_handler
from stickertaggerbot.handlers.labels import create_labels_handler
from stickertaggerbot.handlers.start import create_command_start_handler
from stickertaggerbot.handlers.sticker import create_sticker_handler
